# Generated by Django 4.2 on 2025-03-17 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensorhub', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('value', models.FloatField(verbose_name='valor registrado')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='notas de resolución')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='reconocido')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de reconocimiento')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_warnings', to=settings.AUTH_USER_MODEL, verbose_name='reconocido por')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sensorhub.sensor', verbose_name='sensor')),
            ],
            options={
                'verbose_name': 'advertencia',
                'verbose_name_plural': 'advertencias',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('value', models.FloatField(verbose_name='valor registrado')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='notas de resolución')),
                ('severity', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20, verbose_name='severidad')),
                ('notified', models.BooleanField(default=False, verbose_name='notificado')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='sensorhub.sensor', verbose_name='sensor')),
            ],
            options={
                'verbose_name': 'alarma',
                'verbose_name_plural': 'alarmas',
            },
        ),
    ]
