# Generated by Django 4.2 on 2025-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True, verbose_name='notas de resolución'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True, verbose_name='notas de resolución'),
        ),
    ]
