# Generated by Django 4.2 on 2025-09-16 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rulesengine', '0001_initial'),
        ('events', '0002_alter_alarm_resolution_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='value',
        ),
        migrations.RemoveField(
            model_name='warning',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='warning',
            name='value',
        ),
        migrations.AddField(
            model_name='alarm',
            name='last_value',
            field=models.FloatField(blank=True, null=True, verbose_name='último valor registrado'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='peak_value',
            field=models.FloatField(blank=True, null=True, verbose_name='valor pico durante el incidente'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rulesengine.rule', verbose_name='regla que lo originó'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarm',
            name='triggering_value',
            field=models.FloatField(default=0, verbose_name='valor de activación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarm',
            name='update_count',
            field=models.PositiveIntegerField(default=1, verbose_name='conteo de actualizaciones'),
        ),
        migrations.AddField(
            model_name='warning',
            name='last_value',
            field=models.FloatField(blank=True, null=True, verbose_name='último valor registrado'),
        ),
        migrations.AddField(
            model_name='warning',
            name='peak_value',
            field=models.FloatField(blank=True, null=True, verbose_name='valor pico durante el incidente'),
        ),
        migrations.AddField(
            model_name='warning',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='rulesengine.rule', verbose_name='regla que lo originó'),
        ),
        migrations.AddField(
            model_name='warning',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='fecha de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warning',
            name='triggering_value',
            field=models.FloatField(default=0, verbose_name='valor de activación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warning',
            name='update_count',
            field=models.PositiveIntegerField(default=1, verbose_name='conteo de actualizaciones'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='incidente activo'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='incidente activo'),
        ),
    ]
