# Generated by Django 4.2 on 2025-03-12 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensorhub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'CL'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_stations', to=settings.AUTH_USER_MODEL, verbose_name='propietario'),
        ),
        migrations.AddField(
            model_name='station',
            name='supervisors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'SV'}, related_name='supervised_stations', to=settings.AUTH_USER_MODEL, verbose_name='supervisores'),
        ),
        migrations.AddField(
            model_name='sensormaintenancelog',
            name='performed_by',
            field=models.ForeignKey(limit_choices_to={'company__is_platform_owner': True, 'user_type': 'OP'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='realizado por'),
        ),
        migrations.AddField(
            model_name='sensormaintenancelog',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='sensorhub.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='sensorhub.sensortype', verbose_name='tipo de sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='sensorhub.station', verbose_name='estación'),
        ),
    ]
