# Generated by Django 4.2 on 2025-03-21 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensorhub', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='station',
            name='supervisors',
        ),
        migrations.AddField(
            model_name='station',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.company', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='station',
            name='related_users',
            field=models.ManyToManyField(blank=True, related_name='stations', to=settings.AUTH_USER_MODEL, verbose_name='usuarios asociados'),
        ),
    ]
