# Generated by Django 4.2 on 2025-03-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
        ('sensorhub', '0003_remove_station_owner_remove_station_supervisors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company', verbose_name='empresa'),
        ),
    ]
