# Generated by Django 4.2 on 2025-09-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorhub', '0005_sensortype_color_sensortype_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensortype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sensortype',
            name='site',
        ),
        migrations.AddField(
            model_name='sensor',
            name='color',
            field=models.CharField(blank=True, help_text='Color CSS o HEX, p. ej. #FF8800', max_length=20, null=True, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sitio'),
        ),
    ]
