# Generated by Django 4.2 on 2025-09-06 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorhub', '0006_remove_sensortype_color_remove_sensortype_site_and_more'),
    ]

    operations = [
        # 1) Crear las tablas nuevas primero
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fuente de datos',
                'verbose_name_plural': 'fuentes de datos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('color', models.CharField(blank=True, help_text='Color CSS/HEX para identificar el sistema (opc.)', max_length=20, null=True, verbose_name='color')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sistema/origen',
                'verbose_name_plural': 'sistemas/orígenes',
                'ordering': ['name'],
            },
        ),

        # 2) Agregar los ForeignKey a Sensor (deben existir antes de crear índices)
        migrations.AddField(
            model_name='sensor',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='sensorhub.datasource', verbose_name='fuente de datos'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='sensorhub.sensorsystem', verbose_name='sistema/origen'),
        ),

        # 3) Ahora sí, crear los índices que usan esos campos
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['station', 'system'], name='sensorhub_s_station_e9fe62_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['station', 'source'], name='sensorhub_s_station_dc3272_idx'),
        ),
    ]
