# Generated by Django 4.2 on 2025-09-06 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
        ('sensorhub', '0007_datasource_sensorsystem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('COMPANY', 'Company'), ('SENSOR_TYPE', 'Sensor Type'), ('STATION', 'Station'), ('SENSOR', 'Sensor')], db_index=True, default='SENSOR', help_text='Ámbito al que aplica esta política (la precedencia la decides en tu servicio externo).', max_length=20)),
                ('alert_mode', models.CharField(choices=[('ABS', 'Absoluto'), ('REL', 'Relativo al rango')], default='REL', help_text='ABS: umbrales en unidades del sensor. REL: fracción 0..1 del rango [min,max] del sensor.', max_length=10)),
                ('warn_high', models.FloatField(blank=True, help_text='Umbral de advertencia alto (amarillo).', null=True)),
                ('alert_high', models.FloatField(blank=True, help_text='Umbral de alerta alto (rojo).', null=True)),
                ('enable_low_thresholds', models.BooleanField(default=False, help_text='Activa bandas bajas (warning/alert) para este alcance.')),
                ('warn_low', models.FloatField(blank=True, help_text='Umbral de advertencia bajo (amarillo).', null=True)),
                ('alert_low', models.FloatField(blank=True, help_text='Umbral de alerta bajo (rojo).', null=True)),
                ('hysteresis', models.FloatField(blank=True, help_text='Margen para evitar parpadeo (opcional).', null=True)),
                ('persistence_seconds', models.PositiveIntegerField(blank=True, help_text='Segundos mínimos fuera de banda antes de notificar (opcional).', null=True)),
                ('bands_active', models.BooleanField(default=True, help_text='Permite desactivar esta política sin eliminarla.')),
                ('color_warn', models.CharField(blank=True, help_text='Color para WARNING (ej. #FFC107).', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Use un color HEX válido, p. ej. #FFC107', regex='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('color_alert', models.CharField(blank=True, help_text='Color para ALERT (ej. #DC3545).', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Use un color HEX válido, p. ej. #FFC107', regex='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('description', models.TextField(blank=True, help_text='Comentario opcional (quién/por qué).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Vincular a una compañía (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_policies', to='users.company')),
                ('sensor', models.ForeignKey(blank=True, help_text='Vincular a un sensor específico (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_policies', to='sensorhub.sensor')),
                ('sensor_type', models.ForeignKey(blank=True, help_text='Vincular a un tipo de sensor (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_policies', to='sensorhub.sensortype')),
                ('station', models.ForeignKey(blank=True, help_text='Vincular a una estación (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_policies', to='sensorhub.station')),
            ],
            options={
                'verbose_name': 'política de umbrales',
                'verbose_name_plural': 'políticas de umbrales',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertpolicy',
            index=models.Index(fields=['scope'], name='sensorhub_a_scope_914391_idx'),
        ),
        migrations.AddIndex(
            model_name='alertpolicy',
            index=models.Index(fields=['company'], name='sensorhub_a_company_896993_idx'),
        ),
        migrations.AddIndex(
            model_name='alertpolicy',
            index=models.Index(fields=['sensor_type'], name='sensorhub_a_sensor__709493_idx'),
        ),
        migrations.AddIndex(
            model_name='alertpolicy',
            index=models.Index(fields=['station'], name='sensorhub_a_station_39af65_idx'),
        ),
        migrations.AddIndex(
            model_name='alertpolicy',
            index=models.Index(fields=['sensor'], name='sensorhub_a_sensor__cd0edb_idx'),
        ),
    ]
