# Generated by Django 4.2 on 2025-09-07 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorhub', '0008_alertpolicy_alertpolicy_sensorhub_a_scope_914391_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP del dispositivo, si es diferente a la de la estación.', null=True, verbose_name='dirección IP'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='mqtt_topic',
            field=models.CharField(blank=True, help_text='Topic único donde el sensor publica sus mediciones.', max_length=255, null=True, verbose_name='topic MQTT de datos'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='Puerto de comunicación, si es diferente al de la estación.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='puerto'),
        ),
        migrations.AddField(
            model_name='station',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP del servidor donde recibe los datos.', null=True, verbose_name='dirección IP'),
        ),
        migrations.AddField(
            model_name='station',
            name='mqtt_topic',
            field=models.CharField(blank=True, help_text='Topic para reportar el estado de la estación (ej. "station/123/status").', max_length=255, null=True, verbose_name='topic MQTT de estado'),
        ),
        migrations.AddField(
            model_name='station',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='Puerto de comunicación (ej. 1883 para MQTT).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='puerto'),
        ),
    ]
