# Generated by Django 4.2 on 2025-09-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorhub', '0009_sensor_ip_address_sensor_mqtt_topic_sensor_port_and_more'),
        ('rulesengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='linked_policy',
            field=models.ForeignKey(blank=True, help_text="Usar solo si el tipo de umbral es 'Dinámico'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensorhub.alertpolicy', verbose_name='política de alerta vinculada'),
        ),
        migrations.AddField(
            model_name='condition',
            name='threshold_type',
            field=models.CharField(choices=[('STATIC', 'Estático (valor fijo)'), ('POLICY', 'Dinámico (desde una Política de Alerta)')], default='STATIC', max_length=10, verbose_name='tipo de umbral'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='threshold_config',
            field=models.JSONField(blank=True, default=dict, help_text="Usar solo si el tipo de umbral es 'Estático'. Ej: {'value': 30}", verbose_name='configuración de umbral estático'),
        ),
    ]
