# Generated by Django 4.2 on 2025-03-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensorhub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='fecha y hora')),
                ('value', models.FloatField(verbose_name='valor')),
                ('is_valid', models.BooleanField(default=True, help_text='Indica si el valor está dentro del rango permitido', verbose_name='válido')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='sensorhub.sensor')),
            ],
            options={
                'verbose_name': 'medición',
                'verbose_name_plural': 'mediciones',
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['sensor', 'timestamp'], name='measurement_sensor__aa8663_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['timestamp'], name='measurement_timesta_f98167_idx'),
        ),
    ]
