# Generated by Django 4.2 on 2025-09-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensorhub', '0006_remove_sensortype_color_remove_sensortype_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True, verbose_name='fecha y hora')),
                ('value', models.FloatField(verbose_name='valor')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='sensorhub.sensor')),
            ],
            options={
                'verbose_name': 'medición',
                'verbose_name_plural': 'mediciones',
                'db_table': 'measurements_measurement',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['sensor', 'measured_at'], name='measurement_sensor__967a00_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['measured_at'], name='measurement_measure_86192d_idx'),
        ),
    ]
