# Generated by Django 4.2 on 2025-03-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='fecha y hora')),
                ('value', models.FloatField(verbose_name='valor')),
                ('is_valid', models.BooleanField(default=True, help_text='Indica si el valor está dentro del rango permitido', verbose_name='válido')),
            ],
            options={
                'verbose_name': 'medición',
                'verbose_name_plural': 'mediciones',
            },
        ),
    ]
