# Generated by Django 4.2 on 2025-03-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensorhub', '0001_initial'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='sensorhub.sensor'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['sensor', 'timestamp'], name='measurement_sensor__aa8663_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['timestamp'], name='measurement_timesta_f98167_idx'),
        ),
    ]
