# Generated by Django 4.2 on 2025-03-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'managed': False, 'verbose_name': 'medición', 'verbose_name_plural': 'mediciones'},
        ),
    ]
