# Generated by Django 4.2 on 2025-03-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_measurement_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='measurement',
            table='measurements_measurement',
        ),
    ]
