# Generated by Django 4.2 on 2025-09-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorhub', '0009_sensor_ip_address_sensor_mqtt_topic_sensor_port_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intelligence_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MAINTENANCE', 'Mantenimiento'), ('VALVE_OPERATION', 'Operación de Válvula'), ('GAS_VENTING', 'Venteo de Gas / Mechero'), ('SCHEDULED_STOP', 'Parada Programada'), ('UNSCHEDULED_STOP', 'Parada No Programada'), ('PARAMETER_CHANGE', 'Cambio de Parámetro Operativo'), ('OTHER', 'Otro')], default='OTHER', help_text='Clasificación del evento para facilitar el análisis del modelo.', max_length=50, verbose_name='tipo de evento')),
                ('start_time', models.DateTimeField(help_text='Fecha y hora en que comenzó la operación o el cambio de estado.', verbose_name='inicio del evento')),
                ('end_time', models.DateTimeField(blank=True, help_text='Dejar en blanco si es un cambio de estado permanente o si el evento aún no ha terminado.', null=True, verbose_name='fin del evento')),
                ('description', models.TextField(help_text="Detalles de la operación. Ej: 'Apertura de mechero en espera de instalación de GAE.'", verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_logs', to='sensorhub.station', verbose_name='estación')),
            ],
            options={
                'verbose_name': 'registro operacional',
                'verbose_name_plural': 'registros operacionales',
                'ordering': ['-start_time'],
            },
        ),
    ]
